<?php
/**
 * Plugin Name:       External files from Google Cloud Storage in Media Library
 * Description:       Extends External files in Media Library for usage of Google Cloud Storage.
 * Requires at least: 6.2
 * Requires PHP:      8.1
 * Requires Plugins:  external-files-in-media-library
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       external-files-from-google-cloud-storage
 *
 * @package external-files-from-google-cloud-storage
 */

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// do nothing if PHP-version is not 8.1 or newer.
if ( PHP_VERSION_ID < 80100 ) { // @phpstan-ignore if.alwaysFalse,smaller.alwaysFalse
	return;
}

// bail if "External files in Media Library" is not active.
if( ! in_array( 'external-files-in-media-library/external-files-in-media-library.php', (array) get_option( 'active_plugins', array() ), true ) ) {
	return;
}

use ExternalFilesFromGoogleCloudStorage\Plugin\Init;

// get plugin-path.
const EFMLGCS_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// initialize plugin.
Init::get_instance()->init();
